name: Publish Pre-Release

on:
    release:
        types: [published]

jobs:
    build:
        if: ${{ github.event.release.prerelease }}
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: latest
                cache: npm
            
            - uses: battila7/get-version-action@v2
              id: get_version
            
            - uses: devops-actions/variable-substitution@v1.2
              with:
                files: 'module.json'
              env:
                version: ${{ steps.get_version.outputs.version-without-v }}
                manifest: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.json
                download: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.zip
            
            - run: |
                npm ci
                npm run build

            - run: zip -r9 ./module.zip module.json README.md LICENSE CHANGELOG.md dist/

            - uses: release-flow/keep-a-changelog-action@v3
              id: changelog
              with:
                command: query
                version: ${{ steps.get_version.outputs.version-without-v }}
            
            - uses: ncipollo/release-action@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                allowUpdates: true
                draft: ${{ github.event.release.draft }}
                prerelease: ${{ github.event.release.prerelease }}
                name: ${{ steps.get_version.outputs.version-without-v }}
                body: ${{ steps.changelog.outputs.release-notes }}
                artifacts: './module.json, ./module.zip'